language: bash
services: docker
before_install:
  - cd RestWithSpringboot/
  - echo "We are in the Docker folder!"
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --passwordstdin
deploy:
  provider: script
  script:
    docker push wellmmjr/mysql-rest-with-springboot;
    docker push wellmmjr/rest-with-springboot;
  on:
    branch: master
notifications:
  email: false