version: '3.4'
services:
  db:
    image: wellmmjr/mysql-rest-with-springboot
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root_docker
      MYSQL_USER: usu_docker
      MYSQL_PASSWORD: pass_docker
      MYSQL_DATABASE: rest_with_springboot
    ports:
      - "3308:3306"
    networks:
      - springboot-network
  rest-with-springboot:
    image: wellmmjr/rest-with-springboot
    restart: always
    build: ./RestWithSpringboot
    working_dir: /RestWithSpringboot
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes: 
      - ./RestWithSpringboot:/RestWithSpringboot
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - springboot-network
networks:
    springboot-network:
        driver: bridge